#!/usr/bin/env sh
eval "`./settings.env.sh`"

if $DOCKER_COMMAND volume ls | grep $WORLD_VOLUME_NAME > /dev/null; then
    echo "Found existing world volume $WORLD_VOLUME_NAME."
else
    echo "appdata directory is not present, please run ./setup first."
    exit 1
fi

$DOCKER_COMMAND-compose up -d 
$DOCKER_COMMAND-compose logs -f
