#!/usr/bin/env sh

rm -rf volumes/Plugins/*; cp /home/max/git/space-engineers-ds-plugin/SEScriptUploaderPlugin/ScriptUploaderPlugin/bin/Release/ScriptUploaderPlugin.* volumes/Plugins/  

podman build -t space-engineers-dedicated-docker-linux . 

./pack

podman run \
  --rm \
  -it \
  -v space-engineers-dedicated-docker-linux_world:/appdata/space-engineers/World \
  -v space-engineers-dedicated-docker-linux_plugins:/appdata/space-engineers/Plugins \
  -v space-engineers-dedicated-docker-linux_bins:/appdata/space-engineers/SpaceEngineersDedicated \
  -v space-engineers-dedicated-docker-linux_steamcmd:/home/wine \
  --network host \
  --ulimit nofile=20000:40000 \
  space-engineers-dedicated-docker-linux
